Oz/wine has scripts to build debug versions of Wine for interested parties.

diff --git a/Oz/wine/wine-compat32-debug.SlackBuild b/Oz/wine/wine-compat32-debug.SlackBuild
--- a/Oz/wine/wine-compat32-debug.SlackBuild
+++ b/Oz/wine/wine-compat32-debug.SlackBuild
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-# Slackware build script for wine64 from git tree
+# Slackware build script for wine-compat32 for wine64 from git tree
 
 # Copyright 2010 Ozan Türkyılmaz İstanbul, TUR
 # All rights reserved.
@@ -22,8 +22,10 @@
 # OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 # ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
+# You need to specify wine64 build dir
+# Run it as BDIR64=/path/to/wine64/builddir sh wine-compat32.SlackBuild
 
-PRGNAM=wine64
+PRGNAM=wine-compat32
 VERSION=${VERSION:-1.3.9}
 BUILD=${BUILD:-1}
 TAG=${TAG:-_Oz}
@@ -62,13 +64,21 @@ else
 	LIBDIRSUFFIX=""
 fi
 
+if [ -z BDIR64 ]; then
+	echo Must give wine64 build dir was a argument to the script.
+	exit 1
+fi
+
 rm -rf $PKG
 mkdir -p $TMP $PKG $OUTPUT $TMP/$PRGNAM $BDIR
 
-cd $BDIR
+cd $BDIR64
+$BDIR64=$(pwd)
+
+cd $TMP
 tar xvf $CWD/wine-$VERSION.tar.?z*
 
-# If a patch fails, we ignore it
+# If a patch fails, we ignore it.
 if [ -d $CWD/patch ]; then
 	cd wine-$VERSION
 	for i in $( ls $CWD/patch ); do
@@ -78,9 +88,6 @@ if [ -d $CWD/patch ]; then
 	cd ..
 fi
 
-cd wine-$VERSION
-
-#Changing ownerships
 chown -R root:root .
 find . \
  \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
@@ -89,16 +96,13 @@ find . \
   -exec chmod 644 {} \;
 
 mkdir -p build
-cd build
-
+cd build 
 CFLAGS="$SLKCFLAGS" \
 CXXFLAGS="$SLKCFLAGS" \
 /bin/ash ../configure \
  --prefix=/usr \
- --enable-win64 \
- --libdir=/usr/lib64 \
- --mandir=/usr/man \
- --docdir=/usr/doc/$PRGNAM-$VERSION \
+ --libdir=/usr/lib \
+ --with-wine64=$BDIR64 \
  --build=$ARCH-slackware-linux
 
 if [ "$MAKEDEP" = "yes" ]; then
@@ -123,7 +127,7 @@ cat $CWD/$PRGNAM-SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
 
 #Copying /install
 mkdir -p $PKG/install
-cat $CWD/wine64-debug-slack-desc > $PKG/install/slack-desc
+cat $CWD/wine-compat32-slack-desc > $PKG/install/slack-desc
 cat $CWD/doinst.sh > $PKG/install/doinst.sh
 
 #Creating the package
