General clean up in wine/

diff --git a/wine/wine-compat32.SlackBuild b/wine/wine-compat32.SlackBuild
--- a/wine/wine-compat32.SlackBuild
+++ b/wine/wine-compat32.SlackBuild
@@ -22,13 +22,13 @@
 # OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 # ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
-#You need to specify wine64 build dir as argument to the script.
+# You need to specify wine64 build dir
+# Run it as BDIR64=/path/to/wine64/builddir sh wine-compat32.SlackBuild
 
 PRGNAM=wine-compat32
 VERSION=${VERSION:-1.3.9}
-BUILD=${BUILD:-1} #not really used but still here for future needs.
-TAG=${TAG:-_Oz} #change it for something else If you distrube the packages
-MAKEJOB=${MAKEJOB:-1} #change it as you wish
+BUILD=${BUILD:-1}
+TAG=${TAG:-_Oz}
 PKGTYPE=${PKGTYPE:-tgz}
 
 #automatic ARCH delection from SBo
@@ -45,9 +45,7 @@ CWD=$(pwd)
 TMP=${TMP:-/tmp/Oz}
 PKG=$TMP/package-$PRGNAM
 OUTPUT=${OUTPUT:-/tmp}
-BDIR=$TMP/$PRGNAM
 MAKEDEP=${MAKEDEP:-no}
-BDIR64=""
 
 set -e
 
@@ -66,9 +64,7 @@ else
 	LIBDIRSUFFIX=""
 fi
 
-BDIR64=$1
-
-if [ BDIR64 == "" ]; then
+if [ -z BDIR64 ]; then
 	echo Must give wine64 build dir was a argument to the script.
 	exit 1
 fi
@@ -76,13 +72,17 @@ fi
 rm -rf $PKG
 mkdir -p $TMP $PKG $OUTPUT $TMP/$PRGNAM $BDIR
 
-cd $BDIR
+cd $BDIR64
+$BDIR64=$(pwd)
+
+cd $TMP
 tar xvf $CWD/wine-$VERSION.tar.?z*
 
+# If a patch fails, we ignore it.
 if [ -d $CWD/patch ]; then
 	cd wine-$VERSION
 	for i in $( ls $CWD/patch ); do
-		cat $CWD/patch/$i | patch -p1
+		cat $CWD/patch/$i | patch -p1 || true
 	done
 	autoconf
 	cd ..
@@ -95,10 +95,11 @@ find . \
  \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
   -exec chmod 644 {} \;
 
-cd $BDIR 
+mkdir -p build
+cd build 
 CFLAGS="$SLKCFLAGS" \
 CXXFLAGS="$SLKCFLAGS" \
-$WINE_SRC/configure \
+../configure \
  --prefix=/usr \
  --libdir=/usr/lib \
  --with-wine64=$BDIR64 \
@@ -108,7 +109,7 @@ if [ "$MAKEDEP" = "yes" ]; then
 make depend
 fi
 
-make -j$MAKEJOB
+make
 make install DESTDIR=$PKG
 
 #Strip the binaries
diff --git a/wine/wine.SlackBuild b/wine/wine.SlackBuild
--- a/wine/wine.SlackBuild
+++ b/wine/wine.SlackBuild
@@ -45,7 +45,7 @@ PKG=$TMP/package-$PRGNAM
 OUTPUT=${OUTPUT:-/tmp}
 MAKEDEP=${MAKEDEP:-/no}
 PREFIX=${PREFIX:-/usr}
-MAKEJOB${MAKEJOB:-1}
+
 
 if [ "$ARCH" = "i486" ]; then
   SLKCFLAGS="-O2 -march=i486 -mtune=i686"
@@ -66,10 +66,11 @@ mkdir -p $TMP $PKG $OUTPUT $TMP/$PRGNAM
 cd $TMP
 tar xvf $CWD/wine-$VERSION.tar.?z*
 
+#If a patch fails, we ignore the error
 if [ -d $CWD/patch ]; then
 	cd wine-$VERSION
 	for i in $( ls $CWD/patch ); do
-		cat $CWD/patch/$i | patch -p1
+		cat $CWD/patch/$i | patch -p1 || true
 	done
 	autoconf
 	cd ..
@@ -84,11 +85,12 @@ find . \
  \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
  -exec chmod 644 {} \;
 
-
+mkdir build
+cd build
 # all libs are 32 bit and all builds are out of tree
 CFLAGS="$SLKCFLAGS" \
 CXXFLAGS="$SLKCFLAGS" \
-./configure \
+../configure \
   --prefix=$PREFIX \
   --mandir=$PREFIX/man \
   --docdir=$PREFIX/doc/$PRGNAM-$VERSION \
@@ -99,7 +101,7 @@ if [ "$MAKEDEP" = "yes" ]; then
 make depend
 fi
 
-make -j${MAKEJOB}
+make
 make install DESTDIR=$PKG
 
 
diff --git a/wine/wine64.SlackBuild b/wine/wine64.SlackBuild
--- a/wine/wine64.SlackBuild
+++ b/wine/wine64.SlackBuild
@@ -25,9 +25,8 @@
 
 PRGNAM=wine64
 VERSION=${VERSION:-1.3.9}
-BUILD=${BUILD:-1} #not really used but still here for future needs.
-TAG=${TAG:-_Oz} #change it for something else If you distrube the packages
-MAKEJOB=${MAKEJOB:-1} #change it as you wish
+BUILD=${BUILD:-1}
+TAG=${TAG:-_Oz}
 PKGTYPE=${PKGTYPE:-tgz}
 
 #automatic ARCH delection from SBo
@@ -44,9 +43,7 @@ CWD=$(pwd)
 TMP=${TMP:-/tmp/Oz}
 PKG=$TMP/package-$PRGNAM
 OUTPUT=${OUTPUT:-/tmp}
-BDIR=$TMP/$PRGNAM
 MAKEDEP=${MAKEDEP:-no}
-WINE_SRC=$BDIR/wine-$VERSION
 
 set -e
 
@@ -71,14 +68,17 @@ mkdir -p $TMP $PKG $OUTPUT $TMP/$PRGNAM $BDIR
 cd $BDIR
 tar xvf $CWD/wine-$VERSION.tar.?z*
 
+# If a patch fails, we ignore it
 if [ -d $CWD/patch ]; then
 	cd wine-$VERSION
 	for i in $( ls $CWD/patch ); do
-		cat $CWD/patch/$i | patch -p1
+		cat $CWD/patch/$i | patch -p1 || true
 	done
 	autoconf
 	cd ..
 fi
+
+cd wine-$VERSION
 
 #Changing ownerships
 chown -R root:root .
@@ -88,9 +88,12 @@ find . \
  \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
   -exec chmod 644 {} \;
 
+mkdir -p build
+cd build
+
 CFLAGS="$SLKCFLAGS" \
 CXXFLAGS="$SLKCFLAGS" \
-$WINE_SRC/configure \
+../configure \
  --prefix=/usr \
  --enable-win64 \
  --libdir=/usr/lib64 \
@@ -102,7 +105,7 @@ if [ "$MAKEDEP" = "yes" ]; then
 make depend
 fi
 
-make -j${MAKEJOB}
+make
 make install DESTDIR=$PKG
 
 #Strip the binaries
diff --git a/wine/wow64.SlackBuild b/wine/wow64.SlackBuild
--- a/wine/wow64.SlackBuild
+++ b/wine/wow64.SlackBuild
@@ -25,8 +25,8 @@
 PRGNAM=wine64
 PRGNAM2=wine-compat32
 VERSION="1.3.9"
-BUILD=${BUILD:-1} #not really used but still here for future needs.
-TAG=${TAG:-_Oz} #change it for something else If you distrube the packages
+BUILD=${BUILD:-1}
+TAG=${TAG:-_Oz}
 PKGTYPE=${PKGTYPE:-tgz}
 
 #automatic ARCH delection from SBo
@@ -45,10 +45,9 @@ PKG=$TMP/package-$PRGNAM
 PKG2=$TMP/package-$PRGNAM2
 OUTPUT=${OUTPUT:-/tmp}
 WINE_SRC=$TMP/wine-$VERSION
-BDIR=$TMP/$PRGNAM
-BDIR2=$TMP/$PRGNAM2
+BDIR=$WINE_SRC/build
+BDIR2=$WINE_SRC/build2
 MAKEDEP=${MAKEDEP:-no}
-MAKEJOB=${MAKEJOB:-1}
 
 set -e
 
@@ -72,10 +71,11 @@ mkdir -p $TMP $PKG $PKG2 $OUTPUT $SRC $BDIR $BDIR2
 cd $TMP
 tar xvf $CWD/wine-$VERSION.tar.bz2
 
+# ıf a patch fails, we ignore it.
 if [ -d $CWD/patch ]; then
 	cd wine-$VERSION
 	for i in $( ls $CWD/patch ); do
-		cat $CWD/patch/$i | patch -p1
+		cat $CWD/patch/$i | patch -p1 || true
 	done
 	autoconf
 	cd ..
@@ -107,7 +107,7 @@ if [ "$MAKEDEP" = "yes" ]; then
 make depend
 fi
 
-make -j${MAKEJOB}
+make
 make install DESTDIR=$PKG
 
 
@@ -152,7 +152,7 @@ if [ "$MAKEDEP" = "yes" ]; then
 make depend
 fi
 
-make -j${MAKEJOB}
+make
 make install DESTDIR=$PKG2
 
 #Stript the binaries
